name = "Silo_jll"
uuid = "f5d339c9-093b-5756-8f08-ceae06537255"
version = "4.12.0+0"

[deps]
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
HDF5_jll = "0234f1f7-429e-5d53-9886-15a909be8d59"
MPICH_jll = "7cb0a576-ebde-5e09-9194-50597f1243b4"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
MPItrampoline_jll = "f1f71cc9-e9ae-5b93-9b94-4fe0e1ad3748"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
OpenMPI_jll = "fe0851c0-eecd-5654-98d4-656369965a5c"
MicrosoftMPI_jll = "9237b28f-5490-5468-be7b-bb81f5f5e6cf"

[compat]
MPIPreferences = "0.1"
Zlib_jll = "1.2.12"
Libdl = "< 0.0.1, 1"
HDF5_jll = "2.0.0"
JLLWrappers = "1.7.0"
MPICH_jll = "4.3.0 - 4"
Artifacts = "< 0.0.1, 1"
julia = "1.10"
MPItrampoline_jll = "5.5.3 - 5"
TOML = "< 0.0.1, 1"
OpenMPI_jll = "4.1.8, 5.0.7"
